import { jsPDF } from "jspdf";
import {
  PDF_INK,
  PDF_MARGIN,
  PDF_MUTED,
  PDF_TEXT,
  PDF_VIOLET,
  ensureSpace,
  formattedDate,
  pdfBulletList,
  pdfHeading,
  pdfParagraph,
  pdfRule,
  sanitizeFilename,
} from "./exportService";

export function exportMindMapPdf({ videoTitle, duration, data, imageDataUrl }) {
  const doc = new jsPDF({ unit: "pt", format: "a4" });
  const pageWidth = doc.internal.pageSize.getWidth();
  const pageHeight = doc.internal.pageSize.getHeight();
  const cursor = { y: PDF_MARGIN };

  const nodes = data?.nodes || [];
  const rootLabel = data?.root || "Untitled Topic";

  doc.setFillColor(PDF_INK);
  doc.rect(0, 0, pageWidth, 128, "F");
  doc.setFont("helvetica", "bold");
  doc.setFontSize(20);
  doc.setTextColor("#F2EFE9");
  doc.text("ClipMind AI", PDF_MARGIN, 52);
  doc.setFont("helvetica", "normal");
  doc.setFontSize(11);
  doc.setTextColor(PDF_VIOLET);
  doc.text("AI-Generated Mind Map Report", PDF_MARGIN, 72);
  doc.setFontSize(9);
  doc.setTextColor("#A39FB0");
  doc.text(`Generated ${formattedDate()}`, PDF_MARGIN, 98);

  cursor.y = 128 + 36;
  doc.setFont("helvetica", "bold");
  doc.setFontSize(15);
  doc.setTextColor(PDF_TEXT);
  const titleLines = doc.splitTextToSize(videoTitle || "Untitled video", pageWidth - PDF_MARGIN * 2);
  titleLines.forEach((line) => {
    ensureSpace(doc, cursor, 20, pageHeight);
    doc.text(line, PDF_MARGIN, cursor.y);
    cursor.y += 20;
  });
  doc.setFont("helvetica", "normal");
  doc.setFontSize(10);
  doc.setTextColor(PDF_MUTED);
  doc.text(`Duration: ${duration || "—"}`, PDF_MARGIN, cursor.y);
  cursor.y += 20;

  pdfRule(doc, cursor);
  pdfHeading(doc, cursor, "Mind Map Overview", { color: PDF_VIOLET });
  pdfParagraph(
    doc,
    cursor,
    `This report documents ${nodes.length} concept${nodes.length === 1 ? "" : "s"} branching from the central topic "${rootLabel}", generated by ClipMind's concept-extraction pipeline.`
  );

  if (imageDataUrl) {
    try {
      const maxImgWidth = pageWidth - PDF_MARGIN * 2;
      const props = doc.getImageProperties(imageDataUrl);
      const imgHeight = (props.height * maxImgWidth) / props.width;
      const cappedHeight = Math.min(imgHeight, pageHeight - PDF_MARGIN * 2);
      const cappedWidth = (props.width * cappedHeight) / props.height;
      ensureSpace(doc, cursor, cappedHeight + 20, pageHeight);
      cursor.y += 10;
      doc.setDrawColor("#E4E1DA");
      doc.setLineWidth(1);
      doc.rect(PDF_MARGIN, cursor.y, cappedWidth, cappedHeight);
      doc.addImage(imageDataUrl, "PNG", PDF_MARGIN, cursor.y, cappedWidth, cappedHeight);
      cursor.y += cappedHeight + 20;
    } catch {
      // Image capture is a nice-to-have; the text report still stands on its own.
    }
  }

  nodes.forEach((node) => {
    doc.addPage();
    cursor.y = PDF_MARGIN;
    const detail = node.details || {};

    doc.setFont("helvetica", "bold");
    doc.setFontSize(17);
    doc.setTextColor(PDF_TEXT);
    const nameLines = doc.splitTextToSize(node.title || "Untitled concept", pageWidth - PDF_MARGIN * 2);
    nameLines.forEach((line) => {
      ensureSpace(doc, cursor, 22, pageHeight);
      doc.text(line, PDF_MARGIN, cursor.y);
      cursor.y += 22;
    });
    cursor.y += 6;
    pdfRule(doc, cursor);

    if (detail.what_is_it) {
      pdfHeading(doc, cursor, "What it is", { size: 12, color: PDF_VIOLET, spaceBefore: 8 });
      pdfParagraph(doc, cursor, detail.what_is_it);
    }
    if (detail.role_in_video) {
      pdfHeading(doc, cursor, "Role in this video", { size: 12, color: PDF_VIOLET });
      pdfParagraph(doc, cursor, detail.role_in_video);
    }
    if (detail.how_it_is_used) {
      pdfHeading(doc, cursor, "How it's used", { size: 12, color: PDF_VIOLET });
      pdfParagraph(doc, cursor, detail.how_it_is_used);
    }
    if (detail.why_it_matters) {
      pdfHeading(doc, cursor, "Why it matters", { size: 12, color: PDF_VIOLET });
      pdfParagraph(doc, cursor, detail.why_it_matters);
    }
    if (detail.related_concepts && detail.related_concepts.length > 0) {
      pdfHeading(doc, cursor, "Related concepts", { size: 12, color: PDF_VIOLET });
      pdfBulletList(doc, cursor, detail.related_concepts);
    }

    const hasAnyDetail =
      detail.what_is_it || detail.role_in_video || detail.how_it_is_used || detail.why_it_matters ||
      (detail.related_concepts && detail.related_concepts.length > 0);
    if (!hasAnyDetail) {
      pdfParagraph(doc, cursor, "No further detail was provided for this concept.", { color: PDF_MUTED });
    }
  });

  const pageCount = doc.internal.getNumberOfPages();
  for (let p = 1; p <= pageCount; p++) {
    doc.setPage(p);
    doc.setFont("helvetica", "normal");
    doc.setFontSize(8.5);
    doc.setTextColor("#B5B2AC");
    doc.text("ClipMind AI — Mind Map Report", PDF_MARGIN, pageHeight - 28);
    doc.text(`Page ${p} of ${pageCount}`, pageWidth - PDF_MARGIN - 60, pageHeight - 28);
  }

  doc.save(`${sanitizeFilename(videoTitle)}-mindmap.pdf`);
}
